### ISSUE TITLE
TBProfiler crashes when procession regions with no coverage

### ISSUE THREAD

**Issue by LennertVerboven** [jodyphelan/TBProfiler#86]
Hi

TBProfiler vcf_profile crashes on due to a zerodevisionerror on line 97 when using a vcf file where there are samples which do not have coverage in regions where other samples do have coverage. I am aware of the assumption of good coverage across the genome from TBProfiler, but it would be helpful it TBProfiler would just ignore/skip these areas for the samples which do not have coverage there instead of crashing the program.

Kind regards
Lennert

**Comment by jodyphelan** [comment]
Hi @LennertVerboven this is a very good suggestion. I can skip those regions and try to report which regions have good coverage. I'll try to release a patch for this asap.

Jody

**Comment by jodyphelan** [comment]
This should be fixed in release v2.8.5. Let me know if you have any issue with this again.

Jody

**Comment by LennertVerboven** [comment]
Hi Jody

The error still persists on my system for some sample, I have attached the output of the `bcftools query -u -f '%CHROM\t%POS\t%REF\t%ALT[\t%SAMPLE\t%TBCSQ\t%TGT\t%AD]\n'` commdand. I believe the error stems from line `NC-000962-3-H37Rv	1476297	C	G,*	R04440	non_coding|rrl||rRNA	non_coding|rrl||rRNA	G/G	0,0,0` where this specific sample has no coverage causing the following error:

`Command Failed! Please Check!Exception ignored in: <generator object cmd_out at 0x7f47cd225350>
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/pathogenprofiler/utils.py", line 162, in cmd_out
    exit(1)
  File "/opt/conda/lib/python3.7/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 1
Traceback (most recent call last):
  File "/opt/conda/bin/tb-profiler", line 438, in <module>
    args.func(args)
  File "/opt/conda/bin/tb-profiler", line 292, in main_vcf_profile
    results = pp.vcf_profiler(conf, files_prefix, sample_name, args.tmp_vcf)
  File "/opt/conda/lib/python3.7/site-packages/pathogenprofiler/profiler.py", line 95, in vcf_profiler
    csq = vcf_csq_obj.load_csq(ann_file=conf["ann"])
  File "/opt/conda/lib/python3.7/site-packages/pathogenprofiler/vcf.py", line 97, in load_csq
    adr = {alleles[i]:d/sum(ad) for i,d in enumerate(ad)}
  File "/opt/conda/lib/python3.7/site-packages/pathogenprofiler/vcf.py", line 97, in <dictcomp>
    adr = {alleles[i]:d/sum(ad) for i,d in enumerate(ad)}
ZeroDivisionError: division by zero
`

I have temporarily fixed this by inserting a `if sum(ad) == 0: continue` right before the line throwing the error.

Kind regards
Lennert
[Untitled.txt](https://github.com/jodyphelan/TBProfiler/files/4152480/Untitled.txt)

**Comment by jodyphelan** [comment]
Are you profiling from VCF?

**Comment by LennertVerboven** [comment]
Yes, I am using the vcf_profiler subprogram of tb-profiler, since we have our own custom pipeline which does a few other things that tb-profiler does not provide.

**Comment by jodyphelan** [comment]
Ok, it looks like the issue is with this variant:
```
NC-000962-3-H37Rv	1476297	C	G,*	R04440	non_coding|rrl||rRNA	non_coding|rrl||rRNA	G/G	0,0,0
```
It seems to have zero depth but still have called an alternate allele. Would you mind sharing the VCF or even just the corresponding line for this variant from the VCF?

**Comment by LennertVerboven** [comment]
I have attached a [VCF file](https://github.com/jodyphelan/TBProfiler/files/4152693/x.txt) with the corresponding line and the header line of the vcf. Here you can also see that there is no allelic depth for all different alleles. This is expected behaviour from GATK see [this](https://gatk.broadinstitute.org/hc/en-us/articles/360035532252?id=6005) blogpost. The rrl region being called here is in some places repetitive and commonly associated with mismapping, but we are interested in this region for other purposes than resistance calling. The regions associated with resistance usually do have proper allelic depths, so I think it might be best to skip such a site, only for the sample with no allelic depth, is these cases.

**Comment by jodyphelan** [comment]
Thanks for the info! I have uploaded a patch with the latest commit that should fix the issue. It adds `bcftools view -i 'sum(AD)>0'` to filter out these types of calls when looping through the samples. Do you have access to install the latest github version so you can test before I make a new conda release?

**Comment by LennertVerboven** [comment]
Hi Jody,

Many thanks, this seems to have solved the problem.

Kind regards,
Lennert
